### ISSUE TITLE
Bundle product not saleable

### ISSUE THREAD

**Issue by RiccardoB** [dweeves/magmi-git#157]
I'm trying to import a bundle product on Magento 1.9.0.1 with latest magmi from git but it's not 100% working.

According to wiki ( http://wiki.magmi.org/index.php?title=Bundle_Item_processor ) I've added sku_type, weight_type, price_type, price_view and bundle_skus columns, but not bundle_options column.
I've added all fields (also the optionals) in bundle_skus column.

The product is added to the backend and it looks ok in the editing screens, it's shown in the frontend (category and single product page), but in the product page the "add to cart" button and the box that summarize the bundle options is missing.

I tried to clear the cache and reindex all but the product remains not saleable.

If I go in the backend, enter the product and click "Save", the product become saleable, maybe any database field not correcly compiled by magmi?

Any fix?

**Comment by damienIN** [comment]
I've done this on Magento 1.9.1 with Magmi version 0.7.19. 

I have the bundles importing correctly into Magento.

My CSV format is as so:
store, type,sku,name, sku_type, price_type, weight_type, price_view, weight, price, description, short_description, attribute_set, status, is_in_stock, visibility, categories,bundle_skus,bundle_options

There does appear to be some issue with using imported bundles as related products.

Maybe Dweeves can chime in on this.

**Comment by schuss** [comment]
I have this working, as well, with the following columns:
store,websites,attribute_set,type,sku,category_ids,has_options,name,manufacturer,meta_title,meta_description,image,small_image,url_key,thumbnail,gift_message_available,url_path,custom_design,options_container,price,cost,weight,minimal_price,description,meta_keyword,short_description,custom_layout_update,status,tax_class_id,color,visibility,qty,min_qty,use_config_min_qty,is_qty_decimal,backorders,use_config_backorders,min_sale_qty,use_config_min_sale_qty,max_sale_qty,use_config_max_sale_qty,is_in_stock,low_stock_date,notify_stock_qty,use_config_notify_stock_qty,manage_stock,use_config_manage_stock,stock_status_changed_automatically,related,upsell,crosssell,tier_prices,associated,bundle_options,grouped,sku_type,weight_type,price_type,price_view,bundle_skus

I have a row for each simple product and then a row for the bundle product.  The bundles all come through correctly with one exception:  The bundle items still don't show up on the product detail page on Frontend.  The main bundle sku shows up everywhere - catalog, search, etc. - but there are just no items, and the bundle can't be placed into the cart.

Opening the bundle item in Admin and hitting Save (making no changes at all) corrects whatever setting was incorrectly set by Magmi, and the bundle items then show up on Frontend as expected.  

One quirk: the Quantity of the Bundle item is set to 0 (stock status is still "In Stock") when this save occurs.  So I have been setting my Quantity to "99" for bundle items, so I can easily see in Admin which ones need to be re-Saved (since once they are saved, Quantity goes to 0).  

I wrote a mouse-click macro that opens-and-saves on every item in Admin that I run every time I import new bundles.  Painful and brittle, but it's working.  I haven't been able to figure out what setting is not getting set properly by Magmi.

**Comment by damienIN** [comment]
I would suggest trying to use a smaller amount of columns. Split it into two CSV files, one with the columns I said work as expected, and then another that contains the additional information.

**Comment by RiccardoB** [comment]
Bug fixed here: https://github.com/dweeves/magmi-git/issues/78
