### ISSUE TITLE
Session / request token issue

### ISSUE THREAD

**Issue by richdel** [dweeves/magmi-git#222]
Hi there, I seem to be having an issue where request tokens aren't being sent through properly. Also there appears to be a couple more issues which I feel are all related, when processing csv files the ajax periodical progress updater isn't working but items are being processed fine in the background, also if you enable a plugin and click configure it simply displays a line until hitting save profile then configure again and the options appear.

Output from Custom SQL utility when changing the SQL file:

STK:1513578074551094d490bae1.94842752RTK:

My setup is magmi via a modman clone into the magento root running on nginx/php5-fpm through fcgi socket. I'm guessing it's something to do with the web server config?

**Comment by dweeves** [comment]
indeed, i need to totally rewrite the "foolproof" code for security. i
tried with tokens, but i think i'll force to use an authentication using
the database pass read from the local.xml file from magento.

All this is due to repeated "security alerts" for magmi installs that were
left "open to the web" without any authentication. so i'm obliged to
"protect" all accesses and currently the protection code is buggy.

2015-03-25 2:48 GMT+01:00 richdel <notifications@github.com>:

**Comment by richdel** [comment]
Sorry, somehow missed your response here. OK thanks that makes sense!
