### ISSUE TITLE
Editing attribute_set

### ISSUE THREAD

**Issue by RiccardoB** [dweeves/magmi-git#288]
Hello,
I'm trying to update the attribute set of a product already inserted in Magento, but it looks like MagMi cannot update it.
I have to delete the product and then reimport it.

**Comment by dweeves** [comment]
That's the expected behaviour. magmi do not change attributes nor attribute sets, it only read them to find out how to fill values.

**Comment by RiccardoB** [comment]
Thanks for the info, so the only method available to change the attribute_set of a product is to delete that product and reinsert it (similar to what you do on Magento admin backend)?

**Comment by RiccardoB** [comment]
I think I got misunderstood, I'm not trying to edit a attribute or a attribute_set using MagMi.
I'm trying to change a product X from attribute_set Y to attribute_set Z.
Is this not possible with MagMi?

**Comment by dweeves** [comment]
No this isn't , since attribute_set defines product nature and allowing
this would allow transforming "computer" to "clothes" and would be very
error prone (taking into account that attributes may be totally different).

While not difficult to achieve technically, i currently disabled this type
of behaviour.
The best way to achieve this would be to "delete" & "reimport" the items.

2015-09-24 14:04 GMT+02:00 Riccardo Bianconi <notifications@github.com>:
