### ISSUE TITLE
Set an attribute value to blank for a product

### ISSUE THREAD

**Issue by jasekiw** [dweeves/magmi-git#422]
It does not seem that magmi supports setting an attribute value to blank when importing products.
When a blank attribute is handed to magmi it currently ignores it. We have to currently go back later and set the values to null in order to override this.

We have magmi importing products on a regular basis so having magmi handle this would probably be more efficient than having our own custom code that may not be as efficient.

Is there any magmi codes to use to set the attribute value to null or is this a missing feature?

Thanks,
Jason

**Comment by dweeves** [comment]
\__NULL__ magic value is supported since 0.7.21 to force NULL values in DB.

However, unless explicitely needed (it seems EE has some differences with CE for some requests) , i would recommend to use \__MAGMI_DELETE__ magic value instead to remove the value from an attribute, since it will delete the row in DB instead of forcing a NULL value for the row.

**Comment by jasekiw** [comment]
Thanks for the response. I will try implementing this today. The only reason I am hesitant to use the __MAGMI_DELETE__ is because this import runs so often that I don't want to get a huge number of primary keys. I am using Magento CE so hopefully the __NULL__ magic value should do just fine

Thanks,
Jason

**Comment by jasekiw** [comment]
The __NULL__ magic value is currently setting the value the string "__NULL__" in the database. I am currently running v0.7.21. I could try upgrading and seeing if a newer version will do it.

Thanks,
Jason

**Comment by jasekiw** [comment]
UPDATE: NULL magic values works v0.7.22
