### ISSUE TITLE
On the fly category creator/importer - MySQL error

### ISSUE THREAD

**Issue by patvdleer** [dweeves/magmi-git#485]
When enabling On the fly category creator/importer v0.2.5 I get the error below at every single product in my csv. As soon as I disable the plugin everything does get imported correctly.
```
SKU 11bICE6373-8 - 1 SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'position' at row 1 -
SKU 11bICE6373-8 - 2 SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'position' at row 1 - ERROR ON RECORD #1
```

**Comment by hvanmegen** [comment]
Integer values with quotes? That's not going to work :)

**Comment by patvdleer** [comment]
I'm not sure if the error generates the quotes or if it's the actual empty value.

**Comment by jameswithers** [comment]
The error is because https://github.com/dweeves/magmi-git/blob/master/magmi/engines/magmi_productimportengine.php#L1833 returns null values for category position, which https://github.com/dweeves/magmi-git/blob/master/magmi/engines/magmi_productimportengine.php#L1883 doesn't check are integers before preparing them for database insertion.
